apiVersion: v2
version: 2.8.0-0-main-unstable-2024-11-07-10-48-19-0
name: openebs
appVersion: 2.8.0-0-main-unstable-2024-11-07-10-48-19-0
description: Containerized Attached Storage for Kubernetes
icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
home: https://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - local-storage
  - NVMe
  - storage
  - kubernetes
sources:
  - https://github.com/openebs/openebs
dependencies:
  - name: openebs-crds
    version: 4.1.1
  - name: localpv-provisioner
    version: 4.1.1
    repository: "https://openebs.github.io/dynamic-localpv-provisioner"
  - name: zfs-localpv
    version: 2.7.0-develop
    repository: "https://openebs.github.io/zfs-localpv"
    condition: engines.local.zfs.enabled
  - name: lvm-localpv
    version: 1.6.2
    repository: "https://openebs.github.io/lvm-localpv"
    condition: engines.local.lvm.enabled
  - name: mayastor
    version: 2.8.0-0-main-unstable-2024-11-07-10-48-19-0
    repository: https://openebs.github.io/mayastor-chart-donotuse
    condition: engines.replicated.mayastor.enabled
